participants:

    Calculix:
        interfaces:
        - nodes-mesh: Solid
          patch: surface
          read-data: [Force]
          write-data: [Displacement]
          
precice-config-file: ../precice-config.xml
