participants:
    Solid:
        interfaces:
        - nodes-mesh: Solid-Mesh-nodes
          patch: yend
          read-data: [Temperature]
        - faces-mesh: Solid-Mesh
          patch: flux_interface
          write-data: [Heat-Flux]
        
          
precice-config-file: ../precice-config.xml
