self-hosted-runner:
  labels:
    - precice-tests-vm
# actionlint doesn't yet understand the `$/` self-repository `uses:` syntax.
# See https://github.com/rhysd/actionlint/issues/711.
paths:
  .github/workflows/**/*.{yaml,yml}:
    ignore:
      - reusable workflow call "\$/.+" at "uses" is not following the format
      - specifying action "\$/.+" in invalid format because ref is missing