participants:
    Calculix:
        interfaces:
        - nodes-mesh-with-connectivity: Calculix_Mesh
          patch: interface
          read-data: [Forces0]
          write-data: [DisplacementDeltas0]
          
precice-config-file: ./precice-config.xml

