#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning..."

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Participant 1: Inner-Fluid
Participant1="Inner-Fluid"
cd ${Participant1}
    # Clean the case
    cleanCase
    # Create an empty .foam file for ParaView
    # Note: ".foam" triggers the native OpenFOAM reader of ParaView.
    # Change to ".OpenFOAM" to use the OpenFOAM reader provided with OpenFOAM.
    touch ${Participant1}.foam
cd ..
# Remove the log files
rm -f ${Participant1}_blockMesh.log
rm -f ${Participant1}_checkMesh.log
rm -f ${Participant1}_decomposePar.log
rm -f ${Participant1}.log
rm -f ${Participant1}_reconstructPar.log

# Participant 2: Outer-Fluid
Participant2="Outer-Fluid"
cd ${Participant2}
    # Clean the case
    cleanCase
    # Create an empty .foam file for ParaView
    # Note: ".foam" triggers the native OpenFOAM reader of ParaView.
    # Change to ".OpenFOAM" to use the OpenFOAM reader provided with OpenFOAM.
    touch ${Participant2}.foam
cd ..
# Remove the log files
rm -f ${Participant2}_blockMesh.log
rm -f ${Participant2}_checkMesh.log
rm -f ${Participant2}_decomposePar.log
rm -f ${Participant2}.log
rm -f ${Participant2}_reconstructPar.log

# Participant 3: Solid
Participant3="Solid"
cd ${Participant3}
    # Delete result and log files
    rm -f solid.cvg solid.dat solid.frd solid.sta
cd ..
rm -f Solid.log

# Remove the preCICE-related log files
rm -f convergence-*.log convergence-*.txt
rm -f EventTimings-*.log EventTimings-*.txt
rm -f iterations-*.log iterations-*.txt
rm -f dummy
rm -f spooles.out

echo "Cleaning complete!"
#------------------------------------------------------------------------------
