#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# This script prepares and runs all the participants in one terminal,
# forwarding the solvers' output to log files.
# You need to first download the mesh files separately using the Download_meshes script.
# The script "Allclean" cleans-up the result and log files.

if [ ! -f Solid/all.msh ]; then
    echo "Mesh files not found. Use the Download_meshes script to download them."
    exit
fi

# Participant 1: Inner-Fluid
Participant1="Inner-Fluid"
Solver1="buoyantSimpleFoam"

    # Prepare
    echo "Preparing the ${Participant1} participant..."
    # Copy the backup of the mesh
    cp -r ${Participant1}/constant/polyMesh.org ${Participant1}/constant/polyMesh

    # Run and get the process id
    echo "Starting the ${Participant1} participant..."
    ${Solver1} -case ${Participant1} > ${Participant1}.log 2>&1 &
    PIDParticipant1=$!

# Participant 2: outer-fluid
Participant2="Outer-Fluid"
Solver2="buoyantSimpleFoam"

    # Prepare
    echo "Preparing the ${Participant2} participant..."
    # Copy the backup of the mesh
    cp -r ${Participant2}/constant/polyMesh.org ${Participant2}/constant/polyMesh

    # Run and get the process id
    echo "Starting the ${Participant2} participant..."
    ${Solver2} -case ${Participant2} > ${Participant2}.log 2>&1 &
    PIDParticipant2=$!

# Participant 3: Solid
Participant3="Solid"
Solver3="ccx_preCICE"

    # Run and get the process id
    echo "Starting the ${Participant3} participant..."
    export OMP_NUM_THREADS=1
    export CCX_NPROC_EQUATION_SOLVER=1
    ${Solver3} -i ${Participant3}/solid -precice-participant ${Participant3} > ${Participant3}.log 2>&1 &
    PIDParticipant3=$!

# Wait for all the participants to finish
echo "Waiting for the participants to exit..."
echo "(you may run 'tail -f ${Participant1}.log' in another terminal to check the progress)"
wait ${PIDParticipant1}
wait ${PIDParticipant2}
wait ${PIDParticipant3}
if [ $? -ne 0 ] || [ "$(grep -c -E "error:" ${Participant1}.log)" -ne 0 ] || [ "$(grep -c -E "error:" ${Participant2}.log)" -ne 0 ] || [ "$(grep -c -E "*ERROR" ${Participant3}.log)" -ne 0 ]; then
    echo ""
    echo "Something went wrong... See the log files for more."
else
    echo ""
    echo "The simulation completed!"
    echo "You may now open '${Participant1}/${Participant1}.foam' and '${Participant2}/${Participant2}.foam' in ParaView."
    # Note: ".foam" triggers the native OpenFOAM reader of ParaView.
    # Change to ".OpenFOAM" to use the OpenFOAM reader provided with OpenFOAM.
fi
