#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "This tutorial is based on a case prepared with SimScale."
echo "Since the mesh files are several MB large, we don't store them in the Git repository."
echo "This script downloads and extracts the missing files."
echo ""

echo "Downloading the Solid case..."
curl -s https://syncandshare.lrz.de/dl/fi3c9Xt5UzBc5hJvXzsLBHXn/Solid.tar.gz | tar -xzv

echo "Downloading and extracting the Inner-Fluid mesh..."
curl -s https://syncandshare.lrz.de/dl/fiNsYGC1DKzgio4jS5NhsXg7/polyMesh.org.tar.gz | tar -xzv -C Inner-Fluid/constant

echo "Downloading and extracting the Outer-Fluid mesh..."
curl -s https://syncandshare.lrz.de/dl/fiEZRQ8rcVWRkoyZvANim1R1/polyMesh.org.tar.gz | tar -xzv -C Outer-Fluid/constant

echo "Completed."
