#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "This tutorial is based on a case prepared with SimScale."
echo "Since the mesh files are several MB large, we don't store them in the Git repository."
echo "This script downloads and extracts the missing files."
echo ""

echo "Downloading the Solid case..."
wget https://syncandshare.lrz.de/dl/fi3c9Xt5UzBc5hJvXzsLBHXn/Solid.tar.gz
tar -xzvf Solid.tar.gz
rm Solid.tar.gz

echo "Downloading the Inner-Fluid mesh..."
cd Inner-Fluid/constant
    wget https://syncandshare.lrz.de/dl/fiNsYGC1DKzgio4jS5NhsXg7/polyMesh.org.tar.gz
    tar -xzvf polyMesh.org.tar.gz
    rm polyMesh.org.tar.gz
cd ../..

echo "Downloading the Outer-Fluid mesh..."
cd Outer-Fluid/constant
    wget https://syncandshare.lrz.de/dl/fiEZRQ8rcVWRkoyZvANim1R1/polyMesh.org.tar.gz
    tar -xzvf polyMesh.org.tar.gz
    rm polyMesh.org.tar.gz
cd ../..

echo "Completed."
