#!/usr/bin/env sh
set -e -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

. ../../tools/cleaning-tools.sh

clean_calculix .
rm -fv all.msh # The mesh is generated by generate_mesh.py in this case
