rm -rfv *.abq
rm -rfv *.com
rm -rfv *.dat
rm -rfv *mdl
rm -rfv *.msg
rm -rfv *.odb
rm -rfv *.pac
rm -rfv *.prt
rm -rfv *.res
rm -rfv *.sel
rm -rfv *.sta
rm -rfv *.stt
rm -rfv *.src
rm -rfv *.exception
rm -rfv *.cid
rm -rfv *.lck
rm -rfv *.env
rm -rfv *.simlog
rm -rfv desaii*
rm -rfv *.simdir
rm -fv *.bak
rm -fv *.rpy
rm -fv *_ruc.log
rm -fv *.par
rm -fv *.pes
rm -fv *.pmg
rm -fv *.sim
rm -fv *_nm1.inp
rm -fv stresses.txt
rm -fv log_ruc_run.log