participant: Fluid

precice-config-file: precice-config.xml

interfaces:
- mesh: Fluid-Mesh-Centers
  locations: faceCenters
  patches:
  - flap
  write-data: Force
- mesh: Fluid-Mesh-Nodes
  locations: faceNodes
  patches:
  - flap
  read-data: Displacement

FSIenabled: true
