participant: OpenFOAM

precice-config-file: ../precice-config.xml

interfaces:
- mesh: OpenFOAM-Mesh
  #locations: faceCenters # optional, defaults to faceCenters
  patches:
  - interface
  write-data: Temperature
  read-data: Heat-Flux

CHTenabled: true
