#!/bin/bash

# Fluid participant

# Run this script in one terminal and the "runSolid" script in another terminal.
# These scripts present how the two participants would be started manually.
# Alternatively, you may execute the "Allrun" script in one terminal.

# Run this script with "-parallel" for parallel simulations

# The script "Allclean" cleans-up the result and log files.

# 1 for true, 0 for false
parallel=0
if [ "$1" = "-parallel" ]; then
    parallel=1
fi

echo "Preparing and running the Fluid participant..."

if [ $parallel -eq 1 ]; then
    mpirun -n 2 SU2_CFD Fluid/euler_config_coupled.cfg 2>&1 | tee Fluid.log
else
    SU2_CFD Fluid/euler_config_coupled.cfg 2>&1 | tee Fluid.log
fi
