#!/bin/bash
cd ${0%/*} || exit 1    		    		# Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Fluid participant

# Run this script in one terminal and the "runFluid2" script in another terminal.
# These scripts present how the two participants would be started manually.
# Alternatively, you may execute the "Allrun" script in one terminal.

# Run this script with "-parallel" for parallel simulations

# The script "Allclean" cleans-up the result and log files.

echo "Preparing and running the Fluid2 participant..."

rm -rfv Fluid2/0/
cp -r Fluid2/0.orig/ Fluid2/0/
blockMesh -case Fluid2
checkMesh -case Fluid2

# Run
cd Fluid2
	solver=$(getApplication)
cd ..
$solver -case Fluid2 | tee Fluid2.log 2>&1

foamToVTK -case Fluid2

