rm -rfv *.abq
rm -rfv *.com
rm -rfv *.dat
rm -rfv *mdl
rm -rfv *.msg
rm -rfv *.odb
rm -rfv *.pac
rm -rfv *.prt
rm -rfv *.res
rm -rfv *.sel
rm -rfv *.sta
rm -rfv *.stt
rm -rfv output/*
rm -rfv slurm-*.out
rm -rfv *.src
rm -rfv *.exception
rm -rfv *.cid
rm -rfv *.lck
rm -rfv *.env
rm -rfv *.simlog
rm -r -fv *.log
rm -rfv desaii*
rm -rfv *.simdir
rm -fv *.bak
