#!/usr/bin/env python3
"""
Report resolved Python dependency versions for tutorial requirements.txt files.

Scans every tutorial requirements.txt (excluding tools/tests/), queries PyPI for
the latest version satisfying each constraint, and writes a sibling
requirements-reference.txt next to each file.

Run from the repository root:
  python3 tools/releasing/report_tutorial_requirements.py
  python3 tools/releasing/report_tutorial_requirements.py --check
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib import error, request

from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.utils import canonicalize_name
from packaging.version import Version

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
REFERENCE_NAME = "requirements-reference.txt"
EXCLUDED_RELATIVE = {
    "tools/tests/requirements.txt",
}

_PYPI_VERSIONS_CACHE: dict[str, list[Version]] = {}
_RESOLVED_CACHE: dict[str, str | None] = {}

_HEADER = """\
# Pinned Python dependency versions for this tutorial participant.
# Reference only: run scripts keep using loose requirements.txt constraints.
# Generated by tools/releasing/report_tutorial_requirements.py — do not edit manually.
# Source: {source}
# Generated: {timestamp}

"""


def discover_requirements_files() -> list[Path]:
    """Return git-tracked tutorial requirements.txt files only."""
    result = subprocess.run(
        ["git", "ls-files", "--", "**/requirements.txt"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    files: list[Path] = []
    for line in result.stdout.splitlines():
        relative = line.strip()
        if not relative or relative in EXCLUDED_RELATIVE:
            continue
        files.append(REPO_ROOT / relative)
    return sorted(files)


def reference_path_for(requirements_file: Path) -> Path:
    return requirements_file.with_name(REFERENCE_NAME)


def parse_requirement_line(line: str) -> str | None:
    stripped = line.strip()
    if not stripped or stripped.startswith("#") or stripped.startswith("--"):
        return None
    if " #" in stripped:
        stripped = stripped.split(" #", 1)[0].strip()
    return stripped or None


def fetch_pypi_versions(package_name: str) -> list[Version]:
    canonical = canonicalize_name(package_name)
    if canonical in _PYPI_VERSIONS_CACHE:
        return _PYPI_VERSIONS_CACHE[canonical]

    url = f"https://pypi.org/pypi/{package_name}/json"
    req = request.Request(url, headers={"Accept": "application/json"})
    try:
        with request.urlopen(req, timeout=30) as response:
            payload = json.load(response)
    except error.HTTPError as exc:
        if exc.code == 404:
            return []
        raise

    versions: list[Version] = []
    for version_str in payload.get("releases", {}):
        try:
            versions.append(Version(version_str))
        except Exception:
            continue
    _PYPI_VERSIONS_CACHE[canonical] = versions
    return versions


def resolve_pypi_version(requirement: Requirement) -> str | None:
    cache_key = str(requirement)
    if cache_key in _RESOLVED_CACHE:
        return _RESOLVED_CACHE[cache_key]

    if requirement.url:
        _RESOLVED_CACHE[cache_key] = None
        return None

    versions = fetch_pypi_versions(requirement.name)
    if not versions:
        _RESOLVED_CACHE[cache_key] = None
        return None

    specifier = requirement.specifier if str(requirement.specifier) else SpecifierSet()
    compatible = [version for version in versions if specifier.contains(version, prereleases=False)]
    if not compatible:
        _RESOLVED_CACHE[cache_key] = None
        return None
    resolved = str(max(compatible))
    _RESOLVED_CACHE[cache_key] = resolved
    return resolved


def format_resolved_requirement(requirement_line: str) -> str:
    requirement = Requirement(requirement_line)
    if requirement.url:
        return requirement_line

    resolved = resolve_pypi_version(requirement)
    if resolved is None:
        return f"# {requirement_line}  # non-PyPI (system/PPA or no matching PyPI version)"
    return f"{requirement.name}=={resolved}"


def generate_reference_text(requirements_file: Path, timestamp: str) -> str:
    relative = requirements_file.relative_to(REPO_ROOT).as_posix()
    sections: list[str] = [_HEADER.format(source=relative, timestamp=timestamp)]

    for line in requirements_file.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("--"):
            sections.append(line + "\n")
            continue
        requirement_line = parse_requirement_line(line)
        if requirement_line is None:
            continue
        sections.append(format_resolved_requirement(requirement_line) + "\n")

    return "".join(sections)


def normalize_for_check(text: str) -> str:
    """Ignore generation timestamp when comparing reference files."""
    return re.sub(r"^# Generated: .*\n", "# Generated: <ignored>\n", text, count=1, flags=re.MULTILINE)


def write_all_references() -> list[Path]:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    written: list[Path] = []
    for req_file in discover_requirements_files():
        output = reference_path_for(req_file)
        output.write_text(generate_reference_text(req_file, timestamp))
        written.append(output)
    return written


def check_all_references() -> int:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    missing: list[str] = []
    outdated: list[str] = []

    for req_file in discover_requirements_files():
        output = reference_path_for(req_file)
        relative = output.relative_to(REPO_ROOT).as_posix()
        generated = generate_reference_text(req_file, timestamp)
        if not output.exists():
            missing.append(relative)
            continue
        if normalize_for_check(output.read_text()) != normalize_for_check(generated):
            outdated.append(relative)

    if missing or outdated:
        if missing:
            print("ERROR: missing requirements-reference.txt files:", file=sys.stderr)
            for path in missing:
                print(f"  - {path}", file=sys.stderr)
        if outdated:
            print("ERROR: outdated requirements-reference.txt files:", file=sys.stderr)
            for path in outdated:
                print(f"  - {path}", file=sys.stderr)
        print(
            "Run: python3 tools/releasing/report_tutorial_requirements.py",
            file=sys.stderr,
        )
        return 1

    count = len(discover_requirements_files())
    print(f"OK: {count} requirements-reference.txt file(s) are up to date")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Report resolved tutorial Python dependencies from PyPI"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if any sibling requirements-reference.txt is missing or out of date",
    )
    args = parser.parse_args()

    if args.check:
        return check_all_references()

    written = write_all_references()
    for path in written:
        print(f"Wrote {path.relative_to(REPO_ROOT).as_posix()}")
    print(f"Wrote {len(written)} requirements-reference.txt file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
