#!/usr/bin/env python3
"""
Update sibling requirements-reference.txt files from requirements.txt constraints.

Scans every git-tracked requirements.txt in the repository, queries PyPI for the
latest version satisfying each constraint, and writes a sibling
requirements-reference.txt next to each file.

Run from the repository root:
  python3 tools/releasing/update-requirements-reference.py
  python3 tools/releasing/update-requirements-reference.py --all
  python3 tools/releasing/update-requirements-reference.py path/to/dir
  python3 tools/releasing/update-requirements-reference.py --check
  python3 tools/releasing/update-requirements-reference.py --check --fail-on-outdated
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib import error, request

from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.utils import canonicalize_name
from packaging.version import Version

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
REFERENCE_NAME = "requirements-reference.txt"
SCRIPT_RELATIVE = "tools/releasing/update-requirements-reference.py"
# Empty by default: every tracked requirements.txt gets a sibling reference file.
EXCLUDED_RELATIVE: set[str] = set()

_PYPI_VERSIONS_CACHE: dict[str, list[Version]] = {}
_RESOLVED_CACHE: dict[str, str | None] = {}

_HEADER = """\
# Pinned Python dependency versions for this tutorial participant.
# Reference only: run scripts keep using loose requirements.txt constraints.
# Generated by {script} — do not edit manually.
# Source: {source}
# Generated: {timestamp}

"""


def discover_requirements_files(path: Path | None = None) -> list[Path]:
    """Return git-tracked requirements.txt files, optionally limited to a path."""
    # The `--` separates git options from pathspecs (not a script flag).
    result = subprocess.run(
        ["git", "ls-files", "--", "**/requirements.txt"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    scope: Path | None = None
    if path is not None:
        scope = path if path.is_absolute() else (REPO_ROOT / path)
        scope = scope.resolve()

    files: list[Path] = []
    for line in result.stdout.splitlines():
        relative = line.strip()
        if not relative or relative in EXCLUDED_RELATIVE:
            continue
        candidate = (REPO_ROOT / relative).resolve()
        if scope is not None:
            try:
                candidate.relative_to(scope)
            except ValueError:
                continue
        files.append(candidate)
    return sorted(files)


def reference_path_for(requirements_file: Path) -> Path:
    return requirements_file.with_name(REFERENCE_NAME)


def parse_requirement_line(line: str) -> str | None:
    stripped = line.strip()
    # Skip comments and pip requirement-file options (e.g. --extra-index-url).
    if not stripped or stripped.startswith("#") or stripped.startswith("--"):
        return None
    if " #" in stripped:
        stripped = stripped.split(" #", 1)[0].strip()
    return stripped or None


def fetch_pypi_versions(package_name: str) -> list[Version]:
    canonical = canonicalize_name(package_name)
    if canonical in _PYPI_VERSIONS_CACHE:
        return _PYPI_VERSIONS_CACHE[canonical]

    url = f"https://pypi.org/pypi/{package_name}/json"
    req = request.Request(url, headers={"Accept": "application/json"})
    try:
        with request.urlopen(req, timeout=30) as response:
            payload = json.load(response)
    except error.HTTPError as exc:
        if exc.code == 404:
            return []
        raise

    versions: list[Version] = []
    for version_str in payload.get("releases", {}):
        try:
            versions.append(Version(version_str))
        except Exception:
            continue
    _PYPI_VERSIONS_CACHE[canonical] = versions
    return versions


def resolve_pypi_version(requirement: Requirement) -> str | None:
    cache_key = str(requirement)
    if cache_key in _RESOLVED_CACHE:
        return _RESOLVED_CACHE[cache_key]

    if requirement.url:
        _RESOLVED_CACHE[cache_key] = None
        return None

    versions = fetch_pypi_versions(requirement.name)
    if not versions:
        _RESOLVED_CACHE[cache_key] = None
        return None

    specifier = requirement.specifier if str(requirement.specifier) else SpecifierSet()
    compatible = [version for version in versions if specifier.contains(version, prereleases=False)]
    if not compatible:
        _RESOLVED_CACHE[cache_key] = None
        return None
    resolved = str(max(compatible))
    _RESOLVED_CACHE[cache_key] = resolved
    return resolved


def format_resolved_requirement(requirement_line: str) -> str:
    requirement = Requirement(requirement_line)
    if requirement.url:
        return requirement_line

    resolved = resolve_pypi_version(requirement)
    if resolved is None:
        return f"# {requirement_line}  # non-PyPI (system/PPA or no matching PyPI version)"
    return f"{requirement.name}=={resolved}"


def generate_reference_text(requirements_file: Path, timestamp: str) -> str:
    relative = requirements_file.relative_to(REPO_ROOT).as_posix()
    sections: list[str] = [
        _HEADER.format(script=SCRIPT_RELATIVE, source=relative, timestamp=timestamp)
    ]

    for line in requirements_file.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("--"):
            sections.append(line + "\n")
            continue
        requirement_line = parse_requirement_line(line)
        if requirement_line is None:
            continue
        sections.append(format_resolved_requirement(requirement_line) + "\n")

    return "".join(sections)


def normalize_for_check(text: str) -> str:
    """Ignore generation timestamp when comparing reference files."""
    return re.sub(r"^# Generated: .*\n", "# Generated: <ignored>\n", text, count=1, flags=re.MULTILINE)


def write_references(*, path: Path | None = None, write_all: bool = False) -> tuple[list[Path], list[Path]]:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    written: list[Path] = []
    skipped: list[Path] = []
    for req_file in discover_requirements_files(path):
        output = reference_path_for(req_file)
        generated = generate_reference_text(req_file, timestamp)
        if (
            not write_all
            and output.exists()
            and normalize_for_check(output.read_text()) == normalize_for_check(generated)
        ):
            skipped.append(output)
            continue
        output.write_text(generated)
        written.append(output)
    return written, skipped


def check_references(*, path: Path | None = None, fail_on_outdated: bool = False) -> int:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    missing: list[str] = []
    outdated: list[str] = []

    files = discover_requirements_files(path)
    for req_file in files:
        output = reference_path_for(req_file)
        relative = output.relative_to(REPO_ROOT).as_posix()
        generated = generate_reference_text(req_file, timestamp)
        if not output.exists():
            missing.append(relative)
            continue
        if normalize_for_check(output.read_text()) != normalize_for_check(generated):
            outdated.append(relative)

    if missing:
        print("ERROR: missing requirements-reference.txt files:", file=sys.stderr)
        for entry in missing:
            print(f"  - {entry}", file=sys.stderr)

    if outdated:
        label = "ERROR" if fail_on_outdated else "WARNING"
        print(f"{label}: outdated requirements-reference.txt files:", file=sys.stderr)
        for entry in outdated:
            print(f"  - {entry}", file=sys.stderr)

    if missing or outdated:
        print(
            f"Run: python3 {SCRIPT_RELATIVE}",
            file=sys.stderr,
        )

    if missing or (outdated and fail_on_outdated):
        return 1

    if outdated:
        print(f"OK: {len(files)} requirements-reference.txt file(s) present ({len(outdated)} outdated warning(s))")
    else:
        print(f"OK: {len(files)} requirements-reference.txt file(s) are up to date")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Update sibling requirements-reference.txt files from PyPI"
    )
    parser.add_argument(
        "path",
        nargs="?",
        type=Path,
        help="Optional path to limit updates/checks to requirements.txt files under that directory",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Rewrite all matching reference files even when package pins are unchanged",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check reference files: missing is an error; outdated is a warning unless --fail-on-outdated",
    )
    parser.add_argument(
        "--fail-on-outdated",
        action="store_true",
        help="With --check, also exit 1 when reference files are outdated (for release PRs to master)",
    )
    args = parser.parse_args()

    if args.fail_on_outdated and not args.check:
        parser.error("--fail-on-outdated requires --check")

    if args.check:
        return check_references(path=args.path, fail_on_outdated=args.fail_on_outdated)

    written, skipped = write_references(path=args.path, write_all=args.all)
    for path in written:
        print(f"Wrote {path.relative_to(REPO_ROOT).as_posix()}")
    if skipped:
        print(f"Skipped {len(skipped)} unchanged requirements-reference.txt file(s)")
    print(f"Wrote {len(written)} requirements-reference.txt file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
