#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning..."

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Participant 1: OpenFOAM
Participant1="OpenFOAM"
cd ${Participant1}
    # Clean the case
    cleanCase
    # Create an empty .foam file for ParaView
    # Note: ".foam" triggers the native OpenFOAM reader of ParaView.
    # Change to ".OpenFOAM" to use the OpenFOAM reader provided with OpenFOAM.
    touch ${Participant1}.foam

    # Remove the log files
    rm -fv ${Participant1}_blockMesh.log
    rm -fv ${Participant1}_checkMesh.log
    rm -fv ${Participant1}_decomposePar.log
    rm -fv ${Participant1}.log
    rm -fv ${Participant1}_reconstructPar.log
    rm -fv \
        precice-*.log \
        precice-postProcessingInfo.log \
        precice-*-events.json
cd ..

# Participant 2: Nutils
Participant2="Nutils"
cd ${Participant2}
    echo "Cleaning" ${Participant2}
    rm -fv ${Participant2}.log
    rm -fv *.vtk
    rm -fv \
        precice-*.log \
        precice-*.json
cd ..


# Remove the preCICE address file
rm -fv .${Participant1}-${Participant2}.address

echo "Cleaning complete!"
#------------------------------------------------------------------------------
