#!/bin/bash

# Solid participant

# Run this script in one terminal and the "runFluid" script in another terminal.
# These scripts present how the two participants would be started manually.
# Alternatively, you may execute the "Allrun" script in one terminal.

# The script "Allclean" cleans-up the result and log files.

echo "Preparing and running the Solid participant..."
echo "Note: run the script runFluid first. It sets up a link to the correct precice-config.xml file."

# Prepare in silent mode
cd Solid
    cgx -bg pre_flap.fbd
cd -

# Run
ccx_preCICE -i Solid/flap -precice-participant Calculix