participants:
  # The configuration files for the Inner-Fluid and Outer-Fluid participants
  # are located in each participant's directory.
  Solid:
    interfaces:
    - mesh: Solid-to-Inner-Fluid
      patch: inner-interface
      read-data: [Sink-Temperature-Inner-Fluid, Heat-Transfer-Coefficient-Inner-Fluid]
      write-data: [Sink-Temperature-Solid, Heat-Transfer-Coefficient-Solid]
    - mesh: Solid-to-Outer-Fluid
      patch: outer-interface
      read-data: [Sink-Temperature-Outer-Fluid, Heat-Transfer-Coefficient-Outer-Fluid]
      write-data: [Sink-Temperature-Solid, Heat-Transfer-Coefficient-Solid]
precice-config-file: ../precice-config.xml
