#!/bin/bash
cd ${0%/*} || exit 1    		    		# Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Fluid participant

# Run this script in one terminal and the "runSolid" script in another terminal.
# These scripts present how the two participants would be started manually.
# Alternatively, you may execute the "Allrun" script in one terminal.

# The script "Allclean" cleans-up the result and log files.
run=1
parallel=1

cd Fluid 
	# get application information
	solver=$(getApplication)	# solver
	if [ $parallel -eq 1 ]; then
		np=$(getNumberOfProcessors)	# number of processors
		ln -s -f ../precice-config_parallel.xml precice-config.xml
	else
		ln -s -f ../precice-config_serial.xml precice-config.xml
	fi
cd ..

# Prepare
if [ -f Fluid/blockMesh.log ]; then
	echo "Fluid case is already prepared. "
else
	cd Fluid

	blockMesh > blockMesh.log 2>&1

	checkMesh > checkMesh.log 2>&1

	rm -rf 0
	cp -r 0.orig 0

	cd ..

fi

if [ $run -eq 1 ]; then 
	# Run
	if [ $parallel -eq 1 ]; then
		decomposePar -force -case Fluid > Fluid/decomposePar.log  2>&1
		mpirun -np $np $solver -parallel -case Fluid  > Fluid.log 2>&1
		mv log Fluid/$solver.log
		reconstructPar -case Fluid > Fluid/reconstructPar.log  2>&1 
	else
		#first run with output
		$solver -case Fluid > Fluid.log 2>&1
	fi
fi
