#!/usr/bin/env python3
"""
Report resolved Python dependency versions for tutorial requirements.txt files.

Scans every tutorial requirements.txt (excluding tools/tests/), queries PyPI for
the latest version satisfying each constraint, and writes requirements-reference.txt.

Run from the repository root:
  python3 tools/report_tutorial_requirements.py
  python3 tools/report_tutorial_requirements.py --check
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.utils import canonicalize_name
from packaging.version import Version

REPO_ROOT = Path(__file__).resolve().parent.parent
REFERENCE_FILE = REPO_ROOT / "requirements-reference.txt"
EXCLUDED_RELATIVE = {
    "tools/tests/requirements.txt",
    # Not a pip requirements file (lists stdlib os, unpinned vtk); see develop naming quirk.
    "flow-over-heated-plate/plot-final-interface-temperature-requirements.txt",
}

_PYPI_VERSIONS_CACHE: dict[str, list[Version]] = {}
_RESOLVED_CACHE: dict[str, str | None] = {}

_HEADER = """\
# Pinned Python dependency versions for preCICE tutorial distributions.
# Reference manifest only: tutorial run scripts keep using loose requirements.txt constraints.
# Generated by tools/report_tutorial_requirements.py — do not edit manually.
# Generated: {timestamp}

"""


def discover_requirements_files() -> list[Path]:
    """Return git-tracked tutorial requirements.txt files only."""
    result = subprocess.run(
        ["git", "ls-files", "--", "**/requirements.txt"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    files: list[Path] = []
    for line in result.stdout.splitlines():
        relative = line.strip()
        if not relative or relative in EXCLUDED_RELATIVE:
            continue
        files.append(REPO_ROOT / relative)
    return sorted(files)


def parse_requirement_line(line: str) -> str | None:
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None
    if " #" in stripped:
        stripped = stripped.split(" #", 1)[0].strip()
    return stripped or None


def fetch_pypi_versions(package_name: str) -> list[Version]:
    canonical = canonicalize_name(package_name)
    if canonical in _PYPI_VERSIONS_CACHE:
        return _PYPI_VERSIONS_CACHE[canonical]

    url = f"https://pypi.org/pypi/{package_name}/json"
    request = urllib.request.Request(url, headers={"Accept": "application/json"})
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = json.load(response)
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return []
        raise

    versions: list[Version] = []
    for version_str in payload.get("releases", {}):
        try:
            versions.append(Version(version_str))
        except Exception:
            continue
    _PYPI_VERSIONS_CACHE[canonical] = versions
    return versions


def resolve_pypi_version(requirement: Requirement) -> str | None:
    cache_key = str(requirement)
    if cache_key in _RESOLVED_CACHE:
        return _RESOLVED_CACHE[cache_key]

    if requirement.url:
        _RESOLVED_CACHE[cache_key] = None
        return None

    versions = fetch_pypi_versions(requirement.name)
    if not versions:
        _RESOLVED_CACHE[cache_key] = None
        return None

    specifier = requirement.specifier if str(requirement.specifier) else SpecifierSet()
    compatible = [version for version in versions if specifier.contains(version, prereleases=False)]
    if not compatible:
        _RESOLVED_CACHE[cache_key] = None
        return None
    resolved = str(max(compatible))
    _RESOLVED_CACHE[cache_key] = resolved
    return resolved


def format_resolved_requirement(requirement_line: str) -> str:
    requirement = Requirement(requirement_line)
    if requirement.url:
        return requirement_line

    resolved = resolve_pypi_version(requirement)
    if resolved is None:
        return f"{requirement_line}  # unresolved (not on PyPI or no matching version)"
    return f"{requirement.name}=={resolved}"


def generate_reference_text() -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    sections: list[str] = [_HEADER.format(timestamp=timestamp)]

    for req_file in discover_requirements_files():
        relative = req_file.relative_to(REPO_ROOT).as_posix()
        sections.append(f"# {relative}\n")
        for line in req_file.read_text().splitlines():
            requirement_line = parse_requirement_line(line)
            if requirement_line is None:
                continue
            sections.append(format_resolved_requirement(requirement_line) + "\n")
        sections.append("\n")

    return "".join(sections)


def normalize_for_check(text: str) -> str:
    """Ignore generation timestamp when comparing reference files."""
    return re.sub(r"^# Generated: .*\n", "# Generated: <ignored>\n", text, count=1, flags=re.MULTILINE)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Report resolved tutorial Python dependencies from PyPI"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if requirements-reference.txt is out of date",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REFERENCE_FILE,
        help="Output path (default: requirements-reference.txt at repo root)",
    )
    args = parser.parse_args()

    generated = generate_reference_text()

    if args.check:
        if not args.output.exists():
            print(
                f"ERROR: {args.output} not found. Run: python3 tools/report_tutorial_requirements.py",
                file=sys.stderr,
            )
            return 1
        current = args.output.read_text()
        if normalize_for_check(current) != normalize_for_check(generated):
            print(
                f"ERROR: {args.output} is out of date. Run: python3 tools/report_tutorial_requirements.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {args.output} is up to date")
        return 0

    args.output.write_text(generated)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
