participants:
    Dirichlet:
        interfaces:
        - nodes-mesh: Dirichlet-Mesh
          patch: surface
          read-data: [Displacement]
          write-data: [Force]
          
precice-config-file: ../precice-config.xml
