name: Check style
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with:
         python-version: '3.10'
         check-latest: true
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run checks
        run: pre-commit run -a
