name: Check scripts
on: [push, pull_request]
jobs:
  check_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run:  bash tools/check.sh
      - run:  bash tools/check-size.sh
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1091
