name: Run Testsuite Workflow 
on:
  workflow_call:
    inputs:
      suites:
        description: 'Comma seperated testsuites to execute'
        required: true
        type: string
      build_args:
        description: 'Build arguments'
        required: false
        type: string
      systests_branch:
        description: 'Branch to take the systest from'
        default: 'develop'
        required: true
        type: string
      loglevel:
        description: 'loglevel used for the systemtests'
        default: 'INFO'
        required: false
        type: string
jobs:
  run_testsuite:
    runs-on: [self-hosted, linux, x64, precice-tests-vm]
    steps:
    - name: Display a quick job summary
      run: |
        echo "Initiated by: ${{ github.actor }}"
        echo "Running systemtests --build_args=${{inputs.build_args}} --suites=${{ inputs.suites}}"
        echo "Systemtests branch: ${{ inputs.systests_branch }}"
    - name: Move LFS URL to local LFS server
      run: |
        /home/precice/runners_root/scripts/make_lfs_local.sh
    - name: 'Cleanup the folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
    - name: Check out Tutorials for systest
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.systests_branch }}
        lfs: true
        fetch-depth: 0
    - name: install python depencies
      run: |
        pip install --user -r tools/tests/requirements.txt
    - name: Run tests
      run: |
        cd tools/tests
        python systemtests.py --build_args=${{ inputs.build_args}} --suites=${{ inputs.suites}} --log-level=${{ inputs.loglevel}}
        cd ../../
    - name: Archive run files
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: runs
        path: |
          runs/*