name: Run Testsuite Workflow 
on:
  workflow_call:
    inputs:
      suites:
        description: 'Comma seperated testsuites to execute'
        required: true
        type: string
      build_args:
        description: 'Build arguments'
        required: false
        type: string
      systests_branch:
        description: 'Branch to take the systest from'
        default: 'develop'
        required: true
        type: string
      loglevel:
        description: 'loglevel used for the systemtests'
        default: 'INFO'
        required: false
        type: string
jobs:
  run_testsuite:
    runs-on: ubuntu-latest
    steps:
    - name: Report log
      run: |
        echo "Initiated by: ${{ github.actor }}"
        echo "Running systemtests --build_args=${{github.event.inputs.build_args}} --suites=${{github.event.inputs.suites}}"
        echo "Systemtests branch: ${{ github.event.inputs.systests_branch }}"
    - name: Check out Tutorials for systest
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.systests_branch }}
        lfs: true
        fetch-depth: 0
    - name: Log directory
      run: |
        ls -al
        pwd
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: install python depencies
      run: |
        python -m pip install -r ./tools/tests/requirements.txt
    - name: Expose GitHub Runtime (needed for accessing the gha cache)
      uses: crazy-max/ghaction-github-runtime@v3
    - name: Run tests
      run: |
        cd ./tools/tests
        python systemtests.py --build_args=${{github.event.inputs.build_args}} --suites=${{github.event.inputs.suites}} --log-level=${{github.event.inputs.loglevel}} 
        cd ../../
    - name: Archive run files
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: runs
        path: |
          runs/*