name: Run Testsuite (manual) # Unfortunately, we cannot modify the name: https://github.community/t/github-actions-dynamic-name-of-the-workflow-with-workflow-dispatch/150327
on:
  workflow_dispatch:
    inputs:
      suites:
        description: 'Comma-seperated test suites to execute'
        required: true
        type: string
      build_args:
        description: 'Build arguments (override reference_versions.yaml)'
        required: false
        type: string
      system_tests_branch:
        description: 'Git ref for tools/tests/'
        default: 'develop'
        required: true
        type: string
      upload_artifacts:
        description: 'Upload the complete case files also on success (always true for failure)'
        default: 'TRUE'
        type: choice
        options:
            - 'FALSE'
            - 'TRUE'
      log_level:
        description: 'Logging verbosity of systemtests.py'
        default: 'INFO'
        required: true
        type: choice
        options:
            - 'INFO'
            - 'DEBUG'


jobs:
  run_testsuite_manual:
    uses: ./.github/workflows/run_testsuite_workflow.yml
    with: 
      suites: ${{ inputs.suites }}
      build_args: ${{ inputs.build_args }}
      system_tests_branch: ${{ inputs.system_tests_branch }}
      log_level: ${{ inputs.log_level }}
      upload_artifacts: ${{ inputs.upload_artifacts }}
