name: System tests (PR)

on:
  pull_request:
    types: [labeled]
    
jobs:
  run-system-tests:
    name: Trigger system tests
    if: ${{ github.event.label.name == 'trigger-system-tests' }}
    uses: precice/tutorials/.github/workflows/system-tests.yml@develop
    with:
      suites: release
      build_args: "TUTORIALS_REF:${{ github.event.pull_request.head.sha }}"
      system_tests_branch: develop
      log_level: "INFO"